### ISSUE TITLE
封面的下划线都是蓝色的

### ISSUE THREAD

**Issue by ShijieLi** [mohuangrui/ucasthesis#10]
我直接下载的模版，没作任何修改，编译后发现封面的下划线都是蓝色的，如下图所示，请问如何修改这个颜色？
![2016-03-29 15 26 57](https://cloud.githubusercontent.com/assets/866777/14100833/e6cba922-f5c2-11e5-9fac-22f5fd94b491.png)

**Comment by mohuangrui** [comment]
Hi, this is a really weird situation. I always get black lines when I test on my Linux or Windows systems.

However, I have found the reason, which is due to CJKfntef.sty settings. I have corrected this situation. Please download the latest template and have a try. The updated file is "ucasthesis.cls".

Thank you very much for this feedback and please feel free to tell me if you encounter any problems. Thanks!

**Comment by ShijieLi** [comment]
用了最新版本，确实没这个问题了
辛苦了，非常感谢！

**Comment by mohuangrui** [comment]
You're very welcome, and thank you too for providing that feedback.
I think I could close this issue now. Good luck with your thesis writing!
