### ISSUE TITLE
引用文献在文中应该是上标的形式吧？

### ISSUE THREAD

**Issue by dequn** [mohuangrui/ucasthesis#15]
如题

**Comment by mohuangrui** [comment]
Hi, this depends on your writing style. Personally, I advocate the normal mode like [1], since it's integrated into the content, which makes reading more fluent (the superscripted version induces an sight jumping and interrupts reading). However, if you prefer the traditional way, then go to "commons.sty" at about line 173, find

    \RequirePackage[square,comma,numbers,sort&compress]{natbib}% square bracket
    %\RequirePackage[square,comma,super,sort&compress]{natbib}% superscripted square bracket

simply comment the former line and uncomment the later one :dagger: 

Cheers

**Comment by dequn** [comment]
Thank you !
