### ISSUE TITLE
The UCAS released a new version of the template

### ISSUE THREAD

**Issue by GitatHub** [mohuangrui/ucasthesis#18]
https://github.com/GitatHub/ucasthesis/blob/54caa17e4daeaf1cfb871d2b754f9a85d6ae0fba/%E4%B8%AD%E5%9B%BD%E7%A7%91%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6XX%E4%B8%80%E7%BA%A7%E5%AD%A6%E7%A7%91%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%92%B0%E5%86%99%E8%A7%84%E8%8C%83%E5%8F%8A%E6%A0%BC%E5%BC%8F%E8%8C%83%E4%BE%8B%EF%BC%88%E6%A8%A1%E6%9D%BF%EF%BC%89.doc

the good news is that they clearly request the GB/T style for the referece
and the English cover was revised, which is a ltitle different from your template but similar to https://github.com/xiaoyao9933/UCASthesis 

btw the Abstract should be all capitalized as ABSTRACT, which requie us to change the \def\UCAS@label@englishabstract{Abstract}
 to \def\UCAS@label@englishabstract{ABSTRACT}
in the cfg file.

**Comment by mohuangrui** [comment]
Hello GitatHub,

Thank you for all the work you've done in order to enhance the template. 
I have checked your modifications, and I'm sorry that currently I would 
not consider incorporating your modifications, which is due to that 
those are inconsistent with the official template in the Word version 
released by the UCAS. Again, I appreciate your efforts; however, we 
should use the official guide as a priority and also consider that some 
undefined details may vary according to the institutes and personal 
preferences. Therefore, I would like to maintain the current state.

Thank you very much,
Huangrui

**Comment by GitatHub** [comment]
@HuangruiMo 
Thanks for your prompt response.
I did not try to send a pull request, and I just wanted to remind of that your template is not fully in accord with the official's English cover.

**Comment by mohuangrui** [comment]
Sorry that I didn't see an update of the official template. It would be great if you can provide the official link of the update.

**Comment by GitatHub** [comment]
@mohuangrui  I uploaded the newest version of the offical template onto my repo:
https://github.com/GitatHub/ucasthesis/blob/master/%E4%B8%AD%E5%9B%BD%E7%A7%91%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6XX%E4%B8%80%E7%BA%A7%E5%AD%A6%E7%A7%91%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%92%B0%E5%86%99%E8%A7%84%E8%8C%83%E5%8F%8A%E6%A0%BC%E5%BC%8F%E8%8C%83%E4%BE%8B%EF%BC%88%E6%A8%A1%E6%9D%BF%EF%BC%89.doc  

and here is the link from one inst.
http://www.igg.cas.cn/jyyd/xueweiguanli/jy_xuewei_papers/201612/t20161229_4729332.html

The GB reference style now is required.

**Comment by mohuangrui** [comment]
Thank you very much for your prompt response. I have checked that guide. However, I would not consider any modifications since that guide is not the official guide of UCAS but an adapted version of the igg.cas institute, as you can see "结合中国科学院大学研究生学位论文撰写规定，特制本规范" from the introduction. Thank you again.

**Comment by GitatHub** [comment]
@mohuangrui 
No it's the official version, distributed by the UCAS wit emails system
and many institutes have uploaded to their websites:

e.g.,
http://www.gic.cas.cn/yjsjy/xw/201702/t20170208_4524612.html

OR SEARCH WITH GOOGLE

https://www.google.com/search?q=%E4%B8%AD%E5%9B%BD%E7%A7%91%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6XX%E4%B8%80%E7%BA%A7%E5%AD%A6%E7%A7%91%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%92%B0%E5%86%99%E8%A7%84%E8%8C%83%E5%8F%8A%E6%A0%BC%E5%BC%8F%E8%8C%83%E4%BE%8B%EF%BC%88%E6%A8%A1%E6%9D%BF%EF%BC%89&oq=%E4%B8%AD%E5%9B%BD%E7%A7%91%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6XX%E4%B8%80%E7%BA%A7%E5%AD%A6%E7%A7%91%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%92%B0%E5%86%99%E8%A7%84%E8%8C%83%E5%8F%8A%E6%A0%BC%E5%BC%8F%E8%8C%83%E4%BE%8B%EF%BC%88%E6%A8%A1%E6%9D%BF%EF%BC%89&aqs=chrome..69i57j69i60l2j69i61&sourceid=chrome&ie=UTF-8

**Comment by mohuangrui** [comment]
Sorry that the propagation of that file on the Internet does not provide solid proof of the update. I would not consider until it's release on the UCAS official website. Anyway, thank you.

**Comment by GitatHub** [comment]
Alright.
Thank you and thanks to the lowly efficient UCAS admin. ;)

**Comment by zhanglinbo** [comment]
据我所知，UCAS从未发布过word模板

**Comment by mohuangrui** [comment]
是的，上面所讨论的那个word模板不是UCAS发布的，是一个学生在做了个模板后通过UCAS的学生邮箱系统发给了所有人，部分所的研办又误将其发布到所内，所以才出现了这么一个尴尬的状况。

正如我在模板文档中所声明的，尽管部分所也许对论文格式有不同的设定, LATEX 用户亦无需担心,仍可放
心地使用当前模板进行论文撰写,因为 LATEX 的特征就在于内容与格式的分离。在使用此模板完成论文的撰写后,任何形式的格式调整都可独立于内容进行,并可只需通过修改模板样式文件中的少数命令轻松快速完成,并无风险。
