### ISSUE TITLE
封面信息栏没有下划线

### ISSUE THREAD

**Issue by Terrellz7** [mohuangrui/ucasthesis#340]
## 检查 / Check

- [ ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
使用的是overleaf上最新的模板，已经写了一段时间了，现在发现封面信息栏没有下划线。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![QQ图片20210321201114](https://user-images.githubusercontent.com/49580294/111904391-c5454e80-8a81-11eb-81cc-ad9712441f06.jpg)

**Comment by mohuangrui** [comment]
无法复现问题，刚测了overleaf，使用了xelatex 2019 或 2020 都没有问题

**Comment by muzimuzhi** [comment]
试试放大显示页面？可能下划线太细了

**Comment by ChenyangSi** [comment]
我的也出现这个问题了
<argument> \ULdepth 
                    
l.8 \MAKETITLE
              % 生成英文封面
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
\ulunify #1->\uline 
                    {#1}
l.8 \MAKETITLE
              % 生成英文封面
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by ChenyangSi** [comment]
@mohuangrui 我的也出现这个问题了
\ULdepth

l.8 \MAKETITLE
% 生成英文封面
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., \hobx'), type I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
\ulunify #1->\uline
{#1}
l.8 \MAKETITLE
% 生成英文封面
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., \hobx'), type I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by SukiYume** [comment]
相同的问题，检查`ucasthesis.cls`文件中的
```
%- underline
\ifxetex%
    \RequirePackage{ulem}
```
`\Requier...`是否被注释掉了。

**Comment by ChenyangSi** [comment]
因为 overleaf 的 TeX Live 版本太高了，设置为2019版本就没这个问题了

**Comment by mohuangrui** [comment]
综合大家的信息，问题基本清楚了，应该是 @Terrellz7 使用的版本中出现了 @SukiYume 所说的问题，也即

https://github.com/mohuangrui/ucasthesis/issues/281

中的问题，这个当时已经修复过了，所以我的测试无法复现 @Terrellz7 所说的问题。

**Comment by mohuangrui** [comment]
想起来了，我更新了我的overleaf，但 overleaf 上的发布版忘记更新了。

刚已推送，overleaf 正在审核，一两天后应该就更新了

**Comment by SukiYume** [comment]
好耶 👏🏻👏🏻👏🏻
