### ISSUE TITLE
undefined control sequence "l.35 \makeenglish"

### ISSUE THREAD

**Issue by libingict** [mohuangrui/ucasthesis#4]
Thanks for your contribution. I downloaded the your source could and was ready to use it.
But when I compile the "Thesis.tex" with the pdflatex command, an error occurred as following: 

! Undefined control sequence.
\HyOrg@maketitle ... {4} \UCAS@label@confidential 
                                                  \UCASunderline [30pt]{\UCA...
l.35 \makeenglishtitle
                      
? 

I don't know what's wrong? I did not change anything in your package and I updated my Miktex. 
My pdfTeX, version  is 3.14159265-2.6-1.40.16 (MiKTeX 2.9) and I am using the Ctex suite.

Looking forward to your reply.

**Comment by mohuangrui** [comment]
Hi, please try to check the following things:

1) Try Compile.bat (Windows OS) or Compile.sh (Linux OS) to test the template directly after downloading, if it doesn't work, there may be something wrong with your LaTeX environment.

2) If Compile.bat script works but you failed compiling in your WinEdit, it's because files in \input{} commands are only name indexed and then searched by the Compile script. Using Compile.bat is recommended, if you want to use WinEdit compilation function, please provide the search path for each file inclusion.

3) Generally, xelatex is superior that pdflatex for generating Chinese documents using LaTex.

Cheers

**Comment by libingict** [comment]
Thanks for your help. Today I tried again. However, the Compile.bat did not work either.
When I installed your package on another computer, and it worked well. 
I figured out that the compile error is because my Ctex suite is the SIMPLE one. 
After I installed the FULL version of  the Ctex, everything goes well as far.

Thanks for your help again :)

**Comment by libingict** [comment]
Hi, 
I re-installed my Ctex suite (change from the SIMPLE version  to the FULL one) and the compile.bat worked well so far. There are two more problems haunting me. 

1. When I add my own file (chapter) into the package and run the Complie.bat, my chapter in the output pdf turned to a heap of garbage characters.
On the other hand, if I changed the content in your provided file to my own, the output pdf could be all fine, and both the chinese and english could be showed well. 

What should I do if I want to create my own file and make them work well.

2. Now the title of the subsection is in the middle. If we want it to be in the left, what could we do?

Thanks for your nice help again.

**Comment by mohuangrui** [comment]
Hi,
1) Please make sure all the created source files are using the UTF-8 encoding. You can simply reuse available files to generated UTF-8 encoded files on Windows OS.
2) Please download the latest template (Updated today) to get what you want. The format of the template is improved.

Cheers
