### ISSUE TITLE
hyperref setup when using pdflatex+UTF-8

### ISSUE THREAD

**Issue by mirguest** [mohuangrui/ucasthesis#5]
Dear developers, 

This is just a comment. When I compile this document using pdflatex+UTF-8, the bookmark does not show correctly. 

A solution is add following line:
```tex
\hypersetup{unicode}
```

**Comment by mohuangrui** [comment]
Thank you very much for your comments. Without using \hypersetup{unicode}, the bookmarks don't show correctly when compiling by pdflatex on Linux. Now both pdflatex and xelatex perform well on both Linux and Windows OS after following your suggestions. Thanks a lot!

By the way, may you please tell me why pdflatex is still preferred than xelatex since I have received many feedbacks indicating that preference?
